server:
  port: 8012
spring:
  application:
    name: app-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaypalarora/app-config.git
          username: jaypalarora
          password: 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 #PAT used valid till 29.11.2024
          clone-on-start: true #clones the repo on startup
          default-label: master #default branch
