server:
  port: 8012
spring:
  application:
    name: app-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaypalarora/app-config.git
          username: jaypalarora
          password: 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
          clone-on-start: true
          search-paths: config
          default-label: master
