eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
server:
  port: 0
spring:
  application:
    name: users-ms
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users_ms
    username: postgres
  config:
    import: optional:configserver:http://localhost:8012 #on adding this property bootstrap.properties is not required. This is loaded at startup before any of the beans are created.
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    root: INFO
    com.app.appuserservice.service.AlbumMsRestClient: DEBUG
  file: users-ms.log
token:
  expiration: 3600 #seconds
  secret: locizFuaIgeehRNmRlhlyEerAcGtlNCEtNLSQGIiueBcekFKBolMzkgMDSnzrJpzdxBUctwcDAjMsswWrboXnSDyinGZFsbwUCkvOJqRFtCJiXrtrEOnDqZnbidcIYKsVlpmQlLPuvNLacZtxZLfbgKNbpJzGfFTHbWdbkZPKdwYiubMyinsnPQoOVPLJYSWpIVMNQTroYbBDHFayUagnqOHZkSejSuAsqbAmxgXJWFIlXhnZDQrqNGlXCkHUAyE
gateway:
  ip: "192.168.5.88"
#  Update the above IP for the machine hosting gateway. Use command `hostname -I` on linux.
login:
  url:
    path: /users/login
service-urls:
  album: "http://albums-ms/users/%s/albums"
management:
  endpoints:
    web:
      exposure:
        include: mappings,bus-refresh,bus-env,health,circuitbreakerevents
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      albums-ms:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slidingWindowSize: 2
        slidingWindowType: COUNT_BASED
        failureRateThresholdPercentage: 50
        minimumNumberOfCalls: 1
        eventConsumerBufferSize: 10
  retry:
    #Higher value of aspect order mean higher priority. This will execute @Retry before @CircuitBreaker
    retryAspectOrder: 2
    instances:
      albums-ms:
        waitDuration: 5s
        maxAttempts: 2
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialBackoffInitialInterval: 5000