eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
server:
    port: 0
spring:
    application:
        name: users-ms
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/users-ms
        username: postgres
token:
    expiration: 3600 #seconds
    secret: !QAZxsw2
#gateway:
#    ip: