eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
server:
  port: 0
spring:
  application:
    name: users-ms
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/users_ms
    username: postgres
  config:
    import: optional:configserver:http://localhost:8012 #on adding this property bootstrap.properties is not required. This is loaded at startup before any of the beans are created.
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
token:
  expiration: 3600 #seconds
  secret: locizFuaIgeehRNmRlhlyEerAcGtlNCEtNLSQGIiueBcekFKBolMzkgMDSnzrJpzdxBUctwcDAjMsswWrboXnSDyinGZFsbwUCkvOJqRFtCJiXrtrEOnDqZnbidcIYKsVlpmQlLPuvNLacZtxZLfbgKNbpJzGfFTHbWdbkZPKdwYiubMyinsnPQoOVPLJYSWpIVMNQTroYbBDHFayUagnqOHZkSejSuAsqbAmxgXJWFIlXhnZDQrqNGlXCkHUAyE
gateway:
  ip: "127.0.0.1"
login:
  url:
    path: /users/login
service-urls:
  album: "http://albums-ms/users/%s/albums"