eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8010/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
    file: albums-ms.log
server:
    port: ${PORT:0}
spring:
    application:
        name: albums-ms
    devtools:
        restart:
            enabled: true
