eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  file:
    name: albums-ms.log
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
server:
  port: ${PORT:0}
spring:
  application:
    name: albums-ms
  devtools:
    restart:
      enabled: true
management:
  tracing:
    sampling:
      probability: 1.0